name: Bussiness World CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3.3.0
      
    - name: Setup Node.js enviroment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 18.14.2
        cache: npm
      
    - name: Compilation
      run: npm ci
      
 
